AlpStoriesPraga/Models/Label.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AlpStoriesPraga.Models
{
    public class LabelModel
    {
        public class templates
        {
            public string templateName { get; set; }
        }
        public class product
        {
            public string productId { get; set; }

            public string productName { get; set; }

            public string bgImageTop { get; set; }

            public string bgImageBottom { get; set; }
            public string elements { get; set; }
            public string description { get; set; }

            public string usage { get; set; }

            public string bestBefore { get; set; }

            public string manufacturer { get; set; }

            public float? price { get; set; }

            public int? quantity { get; set; }

            public string barCode { get; set; }

            public string qrCode { get; set; }

            public string icons { get; set; }
            public string template { get; set; }
        }
    }
}

AlpStoriesPraga/Controllers/LabelEditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Dapper;
using AlpStoriesPraga.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.IO;
using SelectPdf;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Text.RegularExpressions;
using HtmlAgilityPack;

namespace AlpStoriesPraga.Controllers
{
    public class LabelEditorController : Controller
    {
        public ActionResult Label()
        {
            return View();
        }

        

        [HttpPost, ValidateInput(false)]
        public JsonResult saveLabel(string productId, string svg)
        {
            //HtmlDocument htmlDocument = new HtmlDocument();
            //htmlDocument.LoadHtml(svg);
            //foreach (var descendant in htmlDocument.DocumentNode.Descendants("metadata").ToList())
            //    descendant.Remove();
            Int32 startIndex = svg.IndexOf("<metadata", StringComparison.Ordinal);

            if (startIndex != -1) {
                var strToRemove = svg.Substring(startIndex, svg.IndexOf("</metadata>", StringComparison.Ordinal) - startIndex + 11);
                svg = svg.Replace(strToRemove, "");
            }
            //svg = htmlDocument.DocumentNode.OuterHtml;

            //svg=Regex.Replace(svg, @"(\</?metadata(.*?)/?\>)", string.Empty, RegexOptions.IgnoreCase);
            //var svg1 = Regex.Replace(svg, @"<*metadata>", String.Empty, RegexOptions.IgnoreCase);
            String dimension;
            System.Web.HttpContext.Current.Session["custom"] = 1;
            if (System.Web.HttpContext.Current.Session["dimension"] == null)
            {
                var cs = ConfigurationManager.ConnectionStrings["alpStories"].ConnectionString;
                using (SqlConnection conn = new SqlConnection(cs))
                {
                    using (SqlCommand cmd = new SqlCommand("dbo.p_getDimension", conn))
                    {
                        conn.Open();
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.Add("@product_id", SqlDbType.NVarChar, 50).Value = productId;
                        cmd.Parameters.Add("@dimension", SqlDbType.Int).Direction = ParameterDirection.Output;
                        cmd.ExecuteNonQuery();
                        dimension = cmd.Parameters["@dimension"].Value.ToString();

                        System.Web.HttpContext.Current.Session["dimension"] = dimension;
                    }
                }
            }
            else
                dimension = System.Web.HttpContext.Current.Session["dimension"].ToString();


            String fileName=System.Web.HttpContext.Current.Session.SessionID + ".svg";
            /*
            if(dimension=="3")
                fileName=System.Web.HttpContext.Current.Session.SessionID + ".svg";
            else
                fileName=System.Web.HttpContext.Current.Session.SessionID + ".svg";
            */
            String filePath = Server.MapPath("~") + @"\Content\UserTemplates\" + fileName;
            String imgName = "";
            System.Web.HttpContext.Current.Session["productId"] = productId;
            /*
            //if I would have base64 encoded
            byte[] data = Convert.FromBase64String(svg);

            System.IO.FileStream _FileStream = new System.IO.FileStream(filePath, System.IO.FileMode.Create, System.IO.FileAccess.Write);
            _FileStream.Write(data, 0, data.Length);
            // close file stream
            _FileStream.Close();
           */

            StreamWriter svgFile = new StreamWriter(filePath, false);
            svgFile.WriteLine(svg);
            svgFile.Close();
            svgFile.Dispose();

            /*create image*/
            int lineCount = 0;
            System.Text.StringBuilder output = new System.Text.StringBuilder();

            string url = ConfigurationManager.AppSettings["UrlImagePath"];
            url += "&id=" + System.Web.HttpContext.Current.Session.SessionID + "&productId=" + productId;

            var p = new System.Diagnostics.Process();
            p.StartInfo.FileName = ConfigurationManager.AppSettings["HtmlToImageExePath"];

            if (dimension == "3")
            {
                imgName = System.Web.HttpContext.Current.Session.SessionID + "_3.jpg";
                p.StartInfo.Arguments = "--width 1134 --height 768 " + url + " " + imgName;
            }
            else
            {
                imgName = System.Web.HttpContext.Current.Session.SessionID + "_1.jpg";
                p.StartInfo.Arguments = "--width 1784 " + url + " " + imgName;
            }

            System.Web.HttpContext.Current.Session["imgName"] = @"../" + ConfigurationManager.AppSettings["ExportImagePath"] + imgName;
            String exportPath = Server.MapPath("~") + ConfigurationManager.AppSettings["ExportImagePath"];

            p.StartInfo.CreateNoWindow = true;
            p.StartInfo.UseShellExecute = false; // needs to be false in order to redirect output
            p.StartInfo.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardError = true;
            p.StartInfo.RedirectStandardInput = true;
            p.StartInfo.WorkingDirectory = exportPath;

            //p.OutputDataReceived += (object sender, DataReceivedEventArgs e) => error=e.Data;
            p.OutputDataReceived += new DataReceivedEventHandler((sender, e) =>
            {
                // Prepend line numbers to each line of the output.
                if (!String.IsNullOrEmpty(e.Data))
                {
                    lineCount++;
                    output.Append("\n[" + lineCount + "]: " + e.Data);
                }
            });

            p.ErrorDataReceived += new DataReceivedEventHandler((sender, e) =>
            {
                // Prepend line numbers to each line of the output.
                if (!String.IsNullOrEmpty(e.Data))
                {
                    lineCount++;
                    output.Append("\n[" + lineCount + "]: " + e.Data);
                }
            });

            p.Start();
            p.BeginOutputReadLine();
            p.BeginErrorReadLine();
            p.WaitForExit();

            if (p.ExitCode != 0)
                throw new Exception(output.ToString());

            p.Close();

            return Json(new { success = true, msg = svg }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getLabel(string productId)
        {
            String label = "";

            if (System.Web.HttpContext.Current.Session["productId"] != null)
            {
                if (System.Web.HttpContext.Current.Session["productId"].ToString() != productId)
                    System.Web.HttpContext.Current.Session["imgName"] = null;
            }
            if (System.Web.HttpContext.Current.Session["imgName"] == null)
            {
                if (System.Web.HttpContext.Current.Session.Contents["label" + productId] == null)
                {
                    var cs = ConfigurationManager.ConnectionStrings["alpStories"].ConnectionString;
                    using (SqlConnection conn = new SqlConnection(cs))
                    {
                        using (SqlCommand cmd = new SqlCommand("dbo.p_getDefaultImage", conn))
                        {
                            conn.Open();
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.Add("@product_id", SqlDbType.NVarChar, 50).Value = productId;
                            SqlDataReader rdr;
                            rdr = cmd.ExecuteReader();
                            rdr.Read();
                            label = rdr.GetString(0);
                            rdr.Close();
                            cmd.ExecuteNonQuery();
                        }
                    }

                    //label = label.Replace("ASTemplates", "TemplatesImg");
                    //label = label.Replace(".svg", ".jpg");
                    System.Web.HttpContext.Current.Session.Contents["label" + productId] = label;
                }
                else
                    label = System.Web.HttpContext.Current.Session.Contents["label" + productId].ToString();

            }
            else
            {
                label=System.Web.HttpContext.Current.Session["imgName"].ToString();
            }
            return Json(new { success = true, msg = label }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public String createPdf()
        {
            string url = "http://localhost/AlpStoriesPraga/labelEditor/template/HP_girl_3";

            int webPageWidth = 1134;
          

            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();
            PdfPageSize pageSize = PdfPageSize.Custom;
            SizeF sz = new SizeF(100, 100);
            converter.Options.PdfPageSize = pageSize;
            converter.Options.PdfPageCustomSize = sz;
            // set converter options
            
            //converter.Options.PdfPageOrientation=;
            converter.Options.WebPageWidth = webPageWidth;
            //converter.Options.WebPageHeight = webPageHeight;

            //HtmlToPdf converter = new HtmlToPdf();
            //converter.Options.WebPageWidth = 96;
            //converter.Options.WebPageHeight = 65;
            converter.Options.MarginTop = 0;
            converter.Options.MarginLeft = 0;
 
            PdfDocument doc = converter.ConvertUrl(url);
            doc.Save(@"d:\Temp\test1.pdf");

            // close pdf document
            doc.Close();

            return "test";
        }

        [HttpGet]
        public JsonResult labelTemplate(String productId)
        {
            LabelModel.product product;

AlpStoriesPraga/Views/LabelEditor/Label.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAlpStories.cshtml";
    ViewBag.Title = "Alp stories";
}

<div class="container">
    <div class="label-editor">
        <div class="row">
            <!------- Hidden element------->
                <input name="load-image" type="file" id="load-image" />
                <div class="templates-wrapper col-xs-12"></div>
                <!---------------------------->
                <div class="nav-bar col-md-4 col-xs-12 col-md-push-8">
                    <!--<div class="title visible-md visible-lg">-->
                    <!--<span>create label</span>-->
                    <!--</div>-->
                    <ul class="nav-property clearfix">
                        <li class="title-save title visible-md visible-lg">
                            <span>Save</span>
                        </li>
                        <li class="title-save title-mobile visible-xs visible-sm">
                            S
                        </li>
                        <!--Upload template-->
                        <li class="template-upload">
                            <section>
                                <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                                <span class="hidden-xs">templates</span>
                            </section>
                        </li>
                        <!-- Upload image-->
                        <li class="image-upload">
                            <section data-toggle="popover">
                                <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
                                <span class="hidden-xs">image</span>
                            </section>
                        </li>
                        <!--Change image-->
                        <li class="image-item-menu">
                            <section data-toggle="popover">
                                <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                                <span class="hidden-xs">Transform</span>
                            </section>
                            <ul class="image-editor nav-property-items clearfix">
                                <li class="image-item col-xs-10 col-sm-5">
                                    <span>Rotate</span>
                                    <div class="slider">
                                        <input class="rotate-slider" type="range" min="0" max="360" step="0.5" value="0" />
                                        <output class="rotate-slider-value">0%</output>
                                    </div>
                                </li>
                                <li class="image-item col-xs-10 col-sm-5">
                                    <span>Scale Image</span>
                                    <div class="slider">
                                        <input class="scale-imade-slider" type="range" min="0" max="2" step="0.001" value="0.2" />
                                        <output class="scale-imade-slider-value">0.2</output>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!--Change text-->
                        <li class="text-item-menu">
                            <section data-toggle="popover">
                                <span class="glyphicon glyphicon-font" aria-hidden="true"></span>
                                <span class="hidden-xs">text</span>
                            </section>
                            <ul class="text-editor nav-property-items clearfix"></ul>
                        </li>
                        <!--Change color-->
                        <li class="color-item-menu">
                            <section data-toggle="popover">
                                <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                                <span class="hidden-xs">color</span>
                            </section>
                            <ul class="color-editor nav-property-items clearfix"></ul>
                        </li>
                    </ul>
                </div>
                <div class="label-wrapper col-md-8 col-xs-12 col-md-pull-4">
                    <div class="label">
                        <div class="ribbon-left">
                            <div class="ribbon-left-top"></div>
                            <div class="ribbon-left-middle"></div>
                            <div class="ribbon-left-bottom"></div>
                        </div>
                        <div id="svg-template"></div>
                        <div class="ribbon-right">
                            <div class="ribbon-right-top">
                                <img src="" alt="" />
                            </div>
                            <div src="#" class="ribbon-right-bottom">
                                <div class="productId"></div>
                                <img src="" alt="" />
                                <div class="productPrice"></div>
                            </div>
                            <div class="ribbon-right-middle">
                                <div class="productBestbefore"></div>
                                <div class="productManufacturer"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
@section Scripts{
<script language="JavaScript">
    var LabelUrlSettings = {
        currentTemplateUrl: '@Url.Action("labelTemplate", "LabelEditor")',
        uploadImageUrl: '@Url.Action("UploadImage", "LabelEditor")',
        getTemplatesUrl: '@Url.Action("getTemplates", "LabelEditor")',
        appPath: '@Server.MapPath("~")',
        rootUrl: '@(Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~"))'
    }
</script>
}

AlpStoriesPraga/Views/LabelEditor/Template.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPdf.cshtml";
}
<div class="label">
    <div class="ribbon-left">
        <div class="css-table" id="cssTableLeft">
            <div class="css-row">
                <div class="css-cell ribbon-left-middle">
                    <div class="ribbon-left-middle-inner">
                        <div class="productElements"></div>
                        <div class="productDescription"></div>
                        <div class="productUsage"></div>
                    </div>
                </div>
            </div>
        </div>
      </div>
        <object id="testTemplate" type="image/svg+xml" data="@ViewBag.Template" class="@ViewBag.css"></object>
        <div class="ribbon-right">
            <div class="css-table" id="cssTableRight">
                <div class="css-row">
                    <div class="css-cell ribbon-right-bottom">
                        <div class="ribbon-right-bottom-box">
                            <div class="inner-rotate" id="inner-rotate">
                                <div class="productId"></div>
                                <img alt="" id="imgBr">
                                <div class="productPrice"></div>
                            </div>
                        </div>
                    </div>

                    <div class="css-cell ribbon-right-middle">
                        <div class="ribbon-right-middle-inner">
                            <div class="productBestbefore rbnText"></div>
                            <div class="productManufacturer"></div>
                        </div>
                    </div>

                    <div class="css-cell ribbon-right-top">
                        <img id="imgQr" alt="">
                    </div>

                </div>
            </div>
        </div>
    </div>

<script type="text/javascript">
    function pausecomp(millis) {
        var date = new Date();
        var curDate = null;

        do { curDate = new Date(); }
        while (curDate - date < millis);
    }
    var productId = '@ViewBag.ProductId';
    var bottleSize = @ViewBag.bottleSize;
    var templateActive;

    $(window).on("load", function () {

        var loadTemplate = function() {
            var ribbonLeft =  $('.ribbon-left');
            var ribbonRight = $('.ribbon-right');
            var obj = $('#testTemplate');
            var svg = $(obj.contents().find('svg')[0]);
            var ribbonEl = $(svg.find('#text_background_left')[0]);
            
            $('.label').css({
                'width': svg.width() +'px',
                'height': svg.height()+'px'
            });
            
            if (svg.find('#text_background_left').length===0) {
                return;
            }
                
            
            
            // Get height and width of ribbons
            

            var ribbonProp = {
                'opacity': ribbonEl.css('opacity'),
                'background': ribbonEl.css('fill')
            };

            if (bottleSize === 1) {
                $('#imgBr').css({
                    'height': 70 +'px',
                    'width': 230 + 'px'
                });

                $('#imgQr').css({
                    'height': 200 +'px',
                    'width': 200 + 'px'
                });

                ribbonLeft.add(ribbonRight).css('font-size', '23px');

            }else if(bottleSize === 3){
                $('#imgBr').css({
                    'height': 42 +'px',
                    'width': 138 + 'px'
                });

                $('#imgQr').css({
                    'height': 140 +'px',
                    'width': 140 + 'px'
                });

                ribbonLeft.add(ribbonRight).css('font-size', '12px');
            }

            $('.ribbon-right-top> img').attr('src', "../" + templateActive.qrCode);
            $('.productBestbefore').html(templateActive.bestBefore);
            $('.productManufacturer').html(templateActive.manufacturer);
            
            $('.productElements').html(templateActive.elements+"<p>");
            $('.productDescription').html(templateActive.description+"<p>");
            $('.productUsage').html(templateActive.usage);

            $('.ribbon-right-bottom img').attr('src', "../" + templateActive.barCode);// + templateActive.barCode);
            $('.productId').html("H10000260002412051630");
            if (templateActive.price)
                $('.productPrice').html("Price: "+templateActive.price +" eur");
            
            var quantity = svg.find('#quantity');
            quantity[0].textContent = templateActive.quantity + " ml" ;

            var ribbonSvgLeft = svg.find('#text_background_left')[0].getBoundingClientRect();
            var ribbonSvgRight = svg.find('#text_background_right')[0].getBoundingClientRect();
            
            //var mainHeight = $('.label').height();
            var mainHeight = Math.floor(ribbonSvgRight.height);
            //var mainWidth = $('.label').width();
            var mainWidth = svg.width();
            //var ribbonHeight = Math.floor(getBounds("cssTableRight").width);
            var rightTable = $('#cssTableRight');
            var leftTable = $('#cssTableLeft');
            var innerRotateWidth = Math.floor(getBounds("inner-rotate").width);
            var innerRotateHeight = Math.floor(getBounds("inner-rotate").height);
            var leftRb = $('.ribbon-left-middle-inner');
            for (var key in ribbonProp) {
                if (ribbonProp.hasOwnProperty(key)) {
                    rightTable.css(key, ribbonProp[key]);
                    leftTable.css(key, ribbonProp[key]);
                    //leftRb.css(key, ribbonProp[key]);
                }
            }

            ribbonLeft.css({
                'top': Math.floor(mainHeight + ribbonSvgLeft.top) + 'px',
                'left':Math.floor(ribbonSvgLeft.left) + 'px',  
                'width': mainHeight + 'px'
            });

            ribbonRight.css({
                'top': Math.floor(mainHeight + ribbonSvgRight.top) + 'px',
                'left':Math.floor(ribbonSvgRight.right) - innerRotateWidth -2  + 'px',  
                'width': mainHeight + 'px'
            });
            
            rightTable.css({
                'height': innerRotateWidth + 'px',
                'width': mainHeight + 'px'
            });

            leftTable.css({
                //'height': innerRotateWidth + 'px',
                'width': mainHeight + 'px'
            });

            $('.ribbon-right-bottom-box').css({
                'width': innerRotateHeight + 'px',
                'height': innerRotateWidth + 'px'
            });
    
            $('.inner-rotate').css({
                'width': innerRotateWidth + 'px',
                'height': innerRotateHeight + 'px',
                'right': -innerRotateWidth + 'px'
            });	
            
        };
        
        function getBounds(ele){
            var bounds = document.getElementById(ele).getBoundingClientRect();
            //console.log(bounds);
            //{left:bounds.left, top:bounds.top,  right:bounds.right, bottom:bounds.bottom}
            return bounds;
        }

        $.ajax({
            url: '@Url.Action("labelTemplate","LabelEditor")' + '/' + productId,
            type: "GET",
            dataType: 'json',
            success: function (data) {
                //pausecomp(5000);
                templateActive = data.template;
                loadTemplate();
            },
            error: function () {
            },
            async: false
        });


    });

</script>

AlpStoriesPraga/Views/LabelEditor/Template_old.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPdf.cshtml";
}
<div class="label">
    <div class="ribbon-left">
        <div class="ribbon-left-top"></div>
        <div class="ribbon-left-middle"></div>
        <div class="ribbon-left-bottom"></div>
    </div>
    <object id="testTemplate" type="image/svg+xml" data="@ViewBag.Template" class="@ViewBag.css"></object>
    <div class="ribbon-right">
        <div src="#" class="ribbon-right-bottom">
            <div class="productId"></div>
            <img id="imgBr" alt="">
            <div class="productPrice"></div>
        </div>
        <div class="ribbon-right-middle">
            <div class="productBestbefore "></div>
            <div class="productManufacturer"></div>
        </div>
        <div class="ribbon-right-top">
            <img id="qrCode" alt="">
        </div>
    </div>
</div>

<script type="text/javascript">
    function pausecomp(millis) {
        var date = new Date();
        var curDate = null;

        do { curDate = new Date(); }
        while (curDate - date < millis);
    }
    var productId = '@ViewBag.ProductId';
    var bottleSize = @ViewBag.bottleSize;

    $(window).on("load", function () {
        
        
            var loadTemplate = function () {
                var //templateActive = getTemplate.data,
                    ribbonLeft = $('.ribbon-left'),
                    ribbonRight = $('.ribbon-right'),
                    $obj = $('#testTemplate'),
                    svg = $($obj.contents().find('svg')[0]);
                    //bottleSize = $('object').attr('data').split('.')[0].split('_').pop();

                    $('.label').css({
                        'width': svg.width(),
                        'height': svg.height()
                    });
                    
                    if (bottleSize > 1) {
                        ribbonLeft.add(ribbonRight).css('font-size', '19px');
                        templateActive.manufacturer=templateActive.manufacturer.replace("136,", "136,<br/>");
                        
                        $('.ribbon-right-bottom > img').css({
                            'height': '90px',
                            'width': '270px'
                        });
                        $('.ribbon-right-top > img').css({
                            'height': '140px',
                            'width': '140px'
                        });
                        $('.ribbon-right-bottom > .productId').css('font-size', '23px');
                    } else {
                        ribbonLeft.add(ribbonRight).css('font-size', '26px');
                        $('.ribbon-right-bottom > img').css({
                            'height': '120px',
                            'width': '300px'
                        });
                        $('.ribbon-right-top > img').css({
                            'height': '150px',
                            'width': '150px'
                        });
                        $('.ribbon-right-bottom > .productId').css('font-size', '23px');
                    }

                //Add data to ribbon
                    $('.ribbon-left-top').html(templateActive.elements);
                    $('.ribbon-left-middle').html(templateActive.description);
                    $('.ribbon-left-bottom').html(templateActive.usage);

                    $('.ribbon-right-top> img').attr('src', "../" + templateActive.qrCode);
                    //$('.productBestbefore :first').html(templateActive.bestBefore);
                //$('.productManufacturer :first').html(templateActive.bestBefore);
                    $('.productBestbefore').html(templateActive.bestBefore);
                    $('.productManufacturer').html(templateActive.manufacturer);
                    //$('.productId').html(templateActive.productId);
                    $('.ribbon-right-bottom img').attr('src', "../../Content/Img/Codes/br.svg");// + templateActive.barCode);
                    if (templateActive.price)
                        $('.productPrice').html("Price: "+templateActive.price +" eur");

                    var ribbonEl = $(svg.find('#text_background_left')[0]);
                    var ribbonProp = {
                        'opacity': ribbonEl.css('opacity'),
                        'background': ribbonEl.css('fill'),
                        'visibility': 'hidden'
                    };

                // Get height and width of ribbons
                    var ribbonSVGLeft = svg.find('#text_background_left')[0].getBoundingClientRect();
                    var ribbonSVGRight = svg.find('#text_background_right')[0].getBoundingClientRect();
                    //var ButtonStripe = svg.find('#Button_Stripe')[0].getBoundingClientRect();

                    var barcCode = $('.ribbon-right-bottom');
                    var leftRibbonWidth = ribbonLeft.width();
                    var rightRibbonWidth = ribbonRight.width();
                    var barcodeWidth = barcCode.width();

                    if (leftRibbonWidth >= rightRibbonWidth) {
                        ribbonProp.height = leftRibbonWidth >= barcodeWidth ? leftRibbonWidth : barcodeWidth;
                    } else {
                        ribbonProp.height = rightRibbonWidth >= barcodeWidth ? rightRibbonWidth : barcodeWidth;
                    }
                    /*ribbonProp.width = ribbonSVGLeft.height;*/
                // Set properties
                    for (var key in ribbonProp) {
                        ribbonRight.css(key, ribbonProp[key]);
                        ribbonLeft.css(key, ribbonProp[key]);
                    }
                    ribbonLeft.css("width", ribbonSVGLeft.height);
                    ribbonRight.css("width", ribbonSVGRight.height);

                    ribbonLeft.add(ribbonRight).css('top', ribbonSVGLeft.height );
                    ribbonLeft.add(ribbonRight).show();


                // Ribbon position trick
                    $('#imgBr').on('load', function () {
                        var paddingBottom = $(".ribbon-right-bottom").height();
                        ribbonLeft.add(ribbonRight).css('visibility', 'visible');
                        
                        $(".ribbon-right-middle").css("padding-left", paddingBottom + 20 + "px");
                        //$('.productManufacturer').html(templateActive.manufacturer);
                        $(".ribbon-right-middle").css("padding-right", "-120px");
                       ribbonLeft.add(ribbonRight).css('visibility', 'visible');
                    });
            }

            $.ajax({
                url: '@Url.Action("labelTemplate","LabelEditor")' + '/' + productId,
                type: "GET",
                dataType: 'json',
                success: function (data) {
                    
                    //pausecomp(5000);
                    templateActive = data.template;
                    loadTemplate();
                },
                error: function () {
                },
                async: false
            });


    });

</script>